{"name": "test_create_duplicate_courier", "status": "failed", "statusDetails": {"message": "AssertionError: Сообщение об ошибке не совпадает\nassert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_scooter_api.TestCourierAPI object at 0x105d4b8f0>\n\n    @allure.feature(\"Создание курьера\")\n    @allure.story(\"2. Нельзя создать двух одинаковых курьеров\")\n    @allure.description(\n        \"Проверка, что нельзя создать двух одинаковых курьеров и ответом приходит \"\n        \"код 409 и сообщение об ошибке'Этот логин уже используется'\"\n    )\n    @allure.step(\n        \"Отправляем POST-запрос на создание курьера с ранее сгенерированными данными снова\"\n    )\n    def test_create_duplicate_courier(self):\n        response = requests.post(f\"{Url.BASE_URL}/courier\", json=self.courier_data)\n        print(\n            f\"Статус после попытки создания дубликата курьера: {response.status_code}\"\n        )\n    \n        assert response.status_code == 409, \"Код ответа не 409 для повторного логина\"\n>       assert (\n            response.json().get(\"message\") == \"Этот логин уже используется\"\n        ), \"Сообщение об ошибке не совпадает\"\nE       AssertionError: Сообщение об ошибке не совпадает\nE       assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\nAPI-tests/test_scooter_api.py:56: AssertionError"}, "description": "Проверка, что нельзя создать двух одинаковых курьеров и ответом приходит код 409 и сообщение об ошибке'Этот логин уже используется'", "steps": [{"name": "Отправляем POST-запрос на создание курьера с ранее сгенерированными данными снова", "status": "failed", "statusDetails": {"message": "AssertionError: Сообщение об ошибке не совпадает\nassert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.\n", "trace": "  File \"/Users/vladvihrov/PycharmProjects/YAProjectSprint_7/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/YAProjectSprint_7/API-tests/test_scooter_api.py\", line 56, in test_create_duplicate_courier\n    assert (\n"}, "start": 1725214446580, "stop": 1725214447051}], "attachments": [{"name": "stdout", "source": "146a59db-6c35-498e-9982-4de275beb896-attachment.txt", "type": "text/plain"}], "start": 1725214446580, "stop": 1725214447053, "uuid": "3c199ea4-4f67-4633-acf9-4bb0e5099319", "historyId": "5f25edd5b6f14621e285bfa4db25891a", "testCaseId": "5f25edd5b6f14621e285bfa4db25891a", "fullName": "API-tests.test_scooter_api.TestCourierAPI#test_create_duplicate_courier", "labels": [{"name": "story", "value": "2. Нельзя создать двух одинаковых курьеров"}, {"name": "feature", "value": "Создание курьера"}, {"name": "parentSuite", "value": "API-tests"}, {"name": "suite", "value": "test_scooter_api"}, {"name": "subSuite", "value": "TestCourierAPI"}, {"name": "host", "value": "MacBook-Pro-Vlad.local"}, {"name": "thread", "value": "18149-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API-tests.test_scooter_api"}]}